In [8]:
import numpy as np; import torch
k = np.array(
    [
        [1,0,-1],
        [2,0,-2],
        [1,0,-1]
    ]).reshape(1,1,3,3).astype(np.float32)

In [9]:
x = np.array(
    [
        [1,1,1,2,3],
        [1,1,1,2,3],
        [1,1,1,2,3],
        [2,2,2,2,3],
        [3,3,3,3,3],
        [4,4,4,4,4]
    ]).reshape(1,1,6,5).astype(np.float32)

In [11]:
conv = torch.nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3,
    bias=False,
    stride = 1,
    padding_mode='zeros',
    padding=0
)

x_tensor = torch.from_numpy(x)
x_tensor.requires_grad = True
conv.weight = torch.nn.Parameter(torch.from_numpy(k))
out = conv(x_tensor)
print(out)

tensor([[[[ 0., -4., -8.],
          [ 0., -3., -7.],
          [ 0., -1., -4.],
          [ 0.,  0., -1.]]]], grad_fn=<ConvolutionBackward0>)


In [12]:
loss = out.sum()
loss.backward()
print(conv.weight.grad)
print(x_tensor.grad)

tensor([[[[15., 18., 25.],
          [21., 23., 28.],
          [30., 31., 34.]]]])
tensor([[[[ 1.,  1.,  0., -1., -1.],
          [ 3.,  3.,  0., -3., -3.],
          [ 4.,  4.,  0., -4., -4.],
          [ 4.,  4.,  0., -4., -4.],
          [ 3.,  3.,  0., -3., -3.],
          [ 1.,  1.,  0., -1., -1.]]]])
